In [23]:
import numpy as np
a=np.array([1,2,3], dtype='int32' )

In [ ]:
#💻 Code: https://github.com/KeithGalli/NumPy

In [8]:
!pip install numpy

In [9]:
print(a)

[1 2 3]


In [10]:
a[2]

3

In [11]:
#numpy is faster than array 
# faster to read less bytes of memory cuz numpy uses less bytes
# no type check when iterating through objects
# numpy uses contiguous memory,simd vector proceesing,effective cache utilization
# insertion, deletion , conctentation etc

In [12]:
b=np.array([1,2,3])
c=np.array([4,5,6])

In [13]:
b*c

array([ 4, 10, 18])

In [14]:
# application : mathematices(matlab replacemt)
#plotting (matplotlib)
# backend(pandas)
# machine learing

In [18]:
p=np.array([[3.0,4.0,4.0],[8.0,8.0,8.0]])

In [19]:
# get dimention
p.ndim

2

In [20]:
# get shape
p.shape

(2, 3)

In [21]:
#memory
# get tupe
p.dtype

dtype('float64')

In [25]:
a.itemsize

4

In [27]:
#total size
a.size

3

In [28]:
p.nbytes

48

In [36]:
# get specific item [r,c]
p=np.array([[3.0,4.0,4.0],[8.0,8.0,8.0]])
p[1,1]

8.0

In [37]:
# get specific row 
p=np.array([[3.0,4.0,4.0],[8.0,8.0,8.0]])
p[0,:]


array([3., 4., 4.])

In [38]:
p[:,1]

array([4., 8.])

In [40]:
#[startindex:endindex:stesize]
p[0,1:3:2]

array([4.])

In [41]:
p[0,1]=3

In [42]:
print(p)

[[3. 3. 4.]
 [8. 8. 8.]]


In [43]:
p[:,1]=[2]

In [44]:
print(p)

[[3. 2. 4.]
 [8. 2. 8.]]


In [45]:
#now 3d 

In [46]:
u=np.array([[[3,4],[4,5],[6,7]]])

In [47]:
print(u)

[[[3 4]
  [4 5]
  [6 7]]]


In [48]:
u[0,1,1]

5

In [49]:
# replace
u[:,1:]=[[8,8],[3,4]]

In [50]:
print(u)

[[[3 4]
  [8 8]
  [3 4]]]


In [53]:
np.zeros((9,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
    

In [54]:
np.full((3,5),88)

array([[88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88]])

In [55]:
# Any other number (full_like)
np.full_like(a, 4)

array([4, 4, 4])

In [57]:
# for random dec
np.random.rand(4,6)

array([[0.79062181, 0.0101772 , 0.97484216, 0.28040667, 0.06373658,
        0.66661575],
       [0.07508585, 0.02501621, 0.26229915, 0.7278871 , 0.17863662,
        0.09940816],
       [0.95423913, 0.17076485, 0.54898801, 0.93812296, 0.65231071,
        0.18307278],
       [0.20902278, 0.003619  , 0.42834452, 0.52762122, 0.91586495,
        0.78134121]])

In [59]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))


array([[-4, -3, -1],
       [ 4,  2,  1],
       [ 7, -3,  6]])

In [60]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
# repeat an array
a=np.array([1,2])
r1=np.repeat(a,3)

In [62]:
print(r1)

[1 1 1 2 2 2]


In [65]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


###problem 1

In [66]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [67]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## cophying

In [68]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# math

In [69]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [70]:
a + 2

array([3, 4, 5, 6])

In [71]:
a - 2

array([-1,  0,  1,  2])

In [72]:
a * 2

array([2, 4, 6, 8])

In [73]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [74]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [75]:
a ** 2

array([ 1,  4,  9, 16])

In [76]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### linear algebra

In [77]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])